### ISSUE TITLE
Can't build on nightly

### ISSUE THREAD

**Issue by jeid64** [alexcrichton/oauth2-rs#2]
Having trouble building the module on my Rust nightly on Ubuntu. I'm currently building master and have tried building the 0.1.8 release.

I'm getting 
src/lib.rs:83:43: 83:52 error: borrowed value does not live long enough
src/lib.rs:83                                      &mut &form[..])

Also tried with rustc 1.0.0-beta.5 (7b4ef47b7 2015-05-11) (built 2015-05-11) and getting the same error.

**Comment by alexcrichton** [comment]
Oh oops, thanks!
