### ISSUE TITLE
a few things I'd like to improve

### ISSUE THREAD

**Issue by lipanski** [alexcrichton/oauth2-rs#8]
hey Alex

here are a few things I'd like improve:

- [x] https://github.com/alexcrichton/oauth2-rs/pull/11 add tests

- [x] https://github.com/alexcrichton/oauth2-rs/pull/13 have all the `exchange_` methods return `Result<Token, TokenError>`, change the `TokenError#error` field to an enum (it's a strict set according to the RFC), but add also an `Other(String)` value to the mix, where I'd map non-traditional errors and (json/form) parse errors

- [x] https://github.com/alexcrichton/oauth2-rs/pull/12 change the interface of `Config` a bit by adding builder-style field setters `set_redirect_url(...) -> Config`, `set_response_type(...) -> Config`, `set_scopes(...) -> Config` (or maybe `add_scope(...) -> Config` and work with one value at a time) so that setting up the whole OAuth2 flow would be as easy as:
    
    ```
    let mut config = Config.new("id", "secret", "http://auth", "http://token").set_redirect_url("http://redirect").set_response_type("authorization_code").set_scopes(...);
    let auth_url = config.authorize_url(...);
    ```

- [ ] ~~determine whether to parse token data *or* error data based on the HTTP status code (but I'd have to see if there's anything about this in the specs or if different implementations handle this properly)~~

- [ ] ~~the RFC says that scopes in the token response are separated by whitespace (not comma), so maybe implement something that handles both. I actually don't think this is so crucial but in some situations the user might authorize less scopes than the app actually requested. Google, for example, doesn't really allow that - you're either in or out.~~

- [x] https://github.com/alexcrichton/oauth2-rs/pull/14 https://github.com/alexcrichton/oauth2-rs/pull/15 add some real-life examples: let's say Google and Github

- [x] https://github.com/alexcrichton/oauth2-rs/pull/16 add some (basic) docs

it depends on how much free time I have so no promises, but in any case I'd like to hear your opinion first :)

**Comment by alexcrichton** [comment]
This all sounds great to me! I unfortunately don't have a huge amount of time to devote to this crate, so if you'd like I can also add you as a collaborator. I don't mind reviewing things though when I can!

**Comment by lipanski** [comment]
@alexcrichton sure, I'd like that. I'll ping you to publish new versions in any case.

**Comment by alexcrichton** [comment]
Ok I've added you as a collaborator!

**Comment by lipanski** [comment]
thanks :cake: 

any things I should keep in mind? should I tag you on PRs? should I make an issue when I need a new version published?

**Comment by alexcrichton** [comment]
Yeah feel free to tag me if you've got questions, but don't feel the need for me to review everything! I'll go ahead and add you as an owner of the crates.io crate as well so you can publish.

**Comment by lipanski** [comment]
better late than never :night_with_stars: I've crossed out most things on the list and a shiny new 1.0.0 is out (containing some breaking changes).

**Comment by lipanski** [comment]
and I've also squeezed myself onto the authors list - hope that's ok :)
